os: osx
osx_image: xcode10.2
language: swift

# branches:
#   only:
#     - develop
#     - master
# env:
#   - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
# before_install:
#   - rvm install ruby-2.2.2
#   - gem install cocoapods
#   - gem install xcpretty -N
#   - brew update
#   - brew install swiftlint || true

script:
  - set -o pipefail
  - xcodebuild -workspace Perfilometro.xcworkspace -scheme Perfilometro -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
 
